name = "15class-history-worker"
main = "src/index.js"
compatibility_date = "2025-05-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "15class-history-db"
database_id = "caaf84d4-e0eb-4533-ad74-e23996e95c43"

[vars]
JWT_SECRET = "/QKcVQlgA24fK3QZwhl/nE57XUDT8fBlhHgq/nqOw88="
CORS_ORIGIN = "*"
